# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: buildAndPush
  displayName: 'Build and push docker images'
  steps:
  - script: docker login -u ${REPOSITORY_PREFIX} -p ${DOCKER_PASSWORD}
    env:
      DOCKER_PASSWORD: $(docker_password)
    displayName: 'Login to dockerhub'
  - script: mvn spring-boot:build-image -Pk8s -DREPOSITORY_PREFIX=${REPOSITORY_PREFIX}
    workingDirectory: lab3
    displayName: 'Build docker images'
  - script: ./scripts/pushImages.sh
    workingDirectory: lab3
    displayName: 'Publish docker images'
- deployment: deployK8s
  dependsOn: buildAndPush
  displayName: Deploy to AKS
  environment: k8s.spring-petclinic
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
        - task: DownloadSecureFile@1
          name: kubeConfig
          displayName: 'Download Kube Config'
          inputs:
            secureFile: 'config'
        - script: kubectl rollout restart deployment -n spring-petclinic --kubeconfig $(kubeConfig.secureFilePath)
          displayName: 'Redeploy'
