# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: docker login -u jostrzol -p ${DOCKER_PASSWORD}
  env:
    DOCKER_PASSWORD: $(docker_password)
  displayName: 'Login to dockerhub'
- script: git clone https://github.com/jostrzol/22z-wus-lab-z9 && cd ./22z-wus-lab-z9/lab3
  displayName: 'Clone repository'
- script: mvn spring-boot:build-image -Pk8s -DREPOSITORY_PREFIX=${REPOSITORY_PREFIX}
  env:
    REPOSITORY_PREFIX: jostrzol
  displayName: 'Build docker images'
- script: ./scripts/pushImages.sh
  env:
    REPOSITORY_PREFIX: jostrzol
  displayName: 'Publish docker images'
