# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: mvn spring-boot:build-image -Pk8s -DREPOSITORY_PREFIX=jostrzol && ./scripts/pushImages.sh
  displayName: 'Build and publish docker image'
