#
# Setup each machine to run docker
#

- hosts: all
  become: yes
  tags: 
    - setup
  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 # One day
      register: result
      until: result is not failed
      retries: 10 # Acquire apt lock
      delay: 4
    - name: Install docker
      apt:
        name: docker
        state: latest
    - name: Install docker.io
      apt:
        name: docker.io
        state: latest
    - name: Addgroup docker
      ansible.builtin.group:
        name: docker
        state: present
    - name: Add {{ ansible_user }} to docker group 
      command: usermod -aG docker {{ ansible_user }}
    - name: reset ssh connection
      meta: reset_connection
      become: no

#
# Install images on each machines and run desired containers
#

- hosts: db_master_vm
  become: yes
  tags: 
  - deploy
  tasks:
    - name: Ensures db_master dir exists
      file: path=/db_master/ state=directory
    - name: Copy master DB Dockerfile # todo: this should be a db-master Dockerfile
      ansible.builtin.copy:
        src: ./db/
        dest: /db_master/
    - name: Stop existing master DB container
      shell: docker stop wus-db-master || true
    - name: Build master DB image
      command: docker build -t wus-db-master /db_master
    - name: Run master DB image
      command: docker run --rm -d -p {{ db_master_port }}:3306 --name wus-db-master wus-db-master

- hosts: db_slave_vm
  become: yes
  tags: 
  - deploy
  tasks:
    - name: Ensures db_slave dir exists
      file: path=/db_slave/ state=directory
    - name: Copy slave DB Dockerfile # todo: this should be a db-slave Dockerfile
      ansible.builtin.copy:
        src: ./db/ 
        dest: /db_slave/
    - name: Stop existing slave DB container
      shell: docker stop wus-db-slave || true
    - name: Build slave DB image
      command: docker build -t wus-db-slave /db_slave
    - name: Run slave DB image
      command: docker run --rm -d -p {{ db_slave_port }}:3306 --name wus-db-slave wus-db-slave

- hosts: be_vm
  become: yes
  tags: 
  - deploy
  tasks:
    - name: Ensures be dir exists
      file: path=/be/ state=directory
    - name: Copy BE Dockerfile
      ansible.builtin.copy:
        src: ./be/
        dest: /be/
    - name: Stop existing BE container(s)
      shell: docker ps -q --filter ancestor=wus-be | xargs --no-run-if-empty docker stop
    - name: Build BE image
      command: docker build -t wus-be /be
    - name: Run BE for writes
      command: docker run --rm -d -p {{ be_write_port }}:8081 -e DB_ADDRESS={{ db_master_host }} -e DB_PORT={{ db_master_port }} wus-be
    - name: Run BE for reads
      command: docker run --rm -d -p {{ be_read_port }}:8081 -e DB_ADDRESS={{ db_slave_host }} -e DB_PORT={{ db_slave_port }} wus-be

- hosts: lb_vm
  become: yes
  tags: 
  - deploy
  tasks:
    - name: Ensures lb dir exists
      file: path=/lb/ state=directory
    - name: Copy LB Dockerfile
      ansible.builtin.copy:
        src: ./lb/
        dest: /lb/
    - name: Stop existing LB container(s)
      shell: docker ps -q --filter ancestor=wus-lb | xargs --no-run-if-empty docker stop
    - name: Build LB image
      command: docker build -t wus-lb /lb
    - name: Run LB
      command: docker run --rm -d -p {{ lb_port }}:8080 -e BE_WRITE_ADDRESS={{ be_write_host }} -e BE_WRITE_PORT={{ be_write_port }} -e BE_READ_ADDRESS={{ be_read_host }} -e BE_READ_PORT={{ be_read_port }} wus-lb


- hosts: fe_vm
  become: yes
  tags: 
  - deploy
  tasks:
    - name: Copy FE Dockerfile
      ansible.builtin.copy:
        src: ./fe/
        dest: /fe/
    - name: Stop existing FE container(s)
      shell: docker ps -q --filter ancestor=wus-fe | xargs --no-run-if-empty docker stop
    - name: Build FE image
      command: docker build -t wus-fe /fe
    - name: Run FE image
      command: docker run --rm -d -p {{ fe_port }}:80 -e BE_ADDRESS={{ lb_host }} -e BE_PORT={{ lb_port }} wus-fe
